VMI Cert: Increase wait timeout for client certificate
ibm-openbmc/bmcweb pull request #113
Opened 2021-09-24 15:19 UTC by rfrandse

This commit is a workaround to fix HMC connection incomplete issue due to VMI delays
in signing client certificate.

we are yet to finalise handling this case. this is a workaround to unblock HMC

2021-09-24 16:13 UTC, sunharis requested changes

2021-09-24 16:13 UTC, sunharis commented on include/ibm/management_console_rest.hpp
>              timeout->async_wait(timeoutHandler);
Please add an info log at the line 905 - once we get the certificate uploaded successfully. This is to enhance the bmcweb trace for the future maintenance

2021-09-24 16:13 UTC, sunharis commented on include/ibm/management_console_rest.hpp
> +                    asyncResp->res, std::to_string(60));
std::to_string(60) can be coded just as "60"

2021-09-27 13:27 UTC, raviteja-b commented
new pr created https://github.com/ibm-openbmc/bmcweb/pull/118

2021-09-27 13:31 UTC, closed without merging