Multipart parser support
ibm-openbmc/bmcweb pull request #132
Opened 2021-10-06 10:31 UTC by sunharis

2021-10-06 10:36 UTC, sunharis commented
Multipart parser is from : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34974

The commit d46c7b6 implements https://github.com/ibm-openbmc/dev/issues/3351 . There is no upstream commit for this command implementation as this is /ibm/v1 path.

Below command works for uploading the multiple save-area files at one go.

_curl -k -H "X-Auth-Token: $bmc_token" -H "Content-Type: multipart/form-data"
-X POST https://${bmc}/ibm/v1/Host/ConfigFiles -F "testfile1=@<path>;type=application/octet-stream"
-F "testfile2=@<path>;type=application/octet-stream"_

2021-10-06 14:04 UTC, asmithakarun commented on include/ibm/management_console_rest.hpp
> +        "/var/lib/bmcweb/ibm-management-console/configfiles";
Can we have a const variable initialized to this on top and use it elsewhere?

2021-10-06 14:05 UTC, asmithakarun commented
Can we fix the CI failure?

2021-10-22 02:44 UTC, gtmills requested changes
We need to discuss more if we want this.

2021-11-29 21:34 UTC, gtmills commented
Can we get this rebased and refreshed to pick up the latest https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/34974 ?

2021-11-30 15:44 UTC, sunharis commented
PR is not yet ready

2021-12-01 05:38 UTC, sunharis commented
https://github.com/ibm-openbmc/bmcweb/pull/180 is created

2021-12-01 05:38 UTC, closed without merging