Fix for not showing PowerSupplies schema under chassis
ibm-openbmc/bmcweb pull request #174
Opened 2021-11-25 16:39 UTC by lkammath

Signed-off-by: Lakshminarayana R. Kammath <lkammath@in.ibm.com>
#166 introduced regression which caused to not show PS schema under chassis because all was moved under macro BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM. 

needed to build bmcweb with BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM and rainier is not doing same so, moving back to original place

2021-11-26 00:47 UTC, ChicagoDuan commented
> needed to build bmcweb with BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM and rainier is not doing same so, moving back to original place

Hi @lkammath  I think PowerSupplies schemas belong to new power subsystem. we need to build bmcweb with BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM if we want to use the new power subsystem.

Why rainier can't build bmcweb with BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM ?

2021-11-26 05:16 UTC, lkammath commented
> > needed to build bmcweb with BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM and rainier is not doing same so, moving back to original place
> 
> Hi @lkammath I think PowerSupplies schemas belong to new power subsystem. we need to build bmcweb with BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM if we want to use the new power subsystem.
> 
> Why rainier can't build bmcweb with BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM ?

I checked the recipe. It is currently not used. I will have to hear from @gtmills about why? Since it is not used till this point i am just reverting back it via this PR

2021-11-26 07:31 UTC, lkammath commented
jenkins test run please

2021-11-28 20:47 UTC, gtmills commented on redfish-core/include/redfish.hpp
>  #ifdef BMCWEB_NEW_POWERSUBSYSTEM_THERMALSUBSYSTEM
We need to enable this then

2021-11-28 20:48 UTC, gtmills requested changes
We need changes to openbmc/openbmc not here

2021-11-28 20:51 UTC, gtmills commented
Don't we already enable this here: https://github.ibm.com/openbmc/openbmc/blob/1020-ghe/meta-ibm/recipes-phosphor/interfaces/bmcweb_%25.bbappend#L5 

What am I missing?

2021-11-29 11:28 UTC, lkammath commented
> Don't we already enable this here: https://github.ibm.com/openbmc/openbmc/blob/1020-ghe/meta-ibm/recipes-phosphor/interfaces/bmcweb_%25.bbappend#L5
> 
> What am I missing?

Sorry, I think i was using very old BMC levels. I will close this

2021-11-29 11:28 UTC, closed without merging