Redfish Assembly: Add More Inventory Types
ibm-openbmc/bmcweb pull request #187
Opened 2021-12-07 14:58 UTC by santoshpuranik

Add the Item.Connector and Item.Drive interfaces to
the list of interfaces we expose as Redfish inventories.

Signed-off-by: Santosh Puranik <santosh.puranik@in.ibm.com>

2021-12-07 14:58 UTC, santoshpuranik commented
I'll update this with validator/testing results soon.

2021-12-07 18:30 UTC, gtmills commented
I'm good with this. Could we push upstream as a commit on top of the assembly stuff?

2021-12-07 18:30 UTC, gtmills approved these changes

2021-12-07 18:31 UTC, gtmills requested changes
Do you also need to add to line 366 ?

2021-12-07 18:32 UTC, gtmills commented
> Do you also need to add to line 366 ?

Ideally we would not have 2 lists of Assembly inventory items

2021-12-08 05:16 UTC, santoshpuranik commented
> > Do you also need to add to line 366 ?
> 
> Ideally we would not have 2 lists of Assembly inventory items

Yes, I do, I was still testing this :) I'll be pushing an update. Yes, ideally we'd want to have these at a common place. Let me see if I can do that too

2021-12-08 12:18 UTC, santoshpuranik commented
> I'm good with this. Could we push upstream as a commit on top of the assembly stuff?

Not sure we want to, wouldn't the interfaces that are considered assemblies vary from company to company?

2021-12-08 14:56 UTC, santoshpuranik commented
Validator results are here: https://sys-openbmc-dev-jenkins.swg-devops.com/job/OpenBMC-Dev/job/test/job/continuous-integration/job/ebmc/job/Redfish-Service-Validator/521/artifact/logs/ConformanceHtmlLog_12_08_2021_113240.html

2021-12-08 15:01 UTC, gtmills approved these changes

2021-12-08 15:50 UTC, SunnySrivastava1984 approved these changes

2021-12-08 16:17 UTC, merged