Redfish: Implement LocationIndicatorActive Property for Manager
ibm-openbmc/bmcweb pull request #219
Opened 2022-01-06 06:21 UTC by ChicagoDuan

Implement LocationIndicatorActive property for Manager.
We can use the following command to set LocationIndicatorActive to true or false:
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"LocationIndicatorActive":false}' https://${bmc}/redfish/v1/Managers/bmc

Signed-off-by: Chicago Duan <duanzhijia01@inspur.com>

2022-01-06 10:26 UTC, santoshpuranik requested changes

2022-01-07 01:01 UTC, ChicagoDuan commented on redfish-core/lib/managers.hpp
> +                if (managerName != "bmc")
I considered the situation of multiple Managers. If there is no such situation, I will modify it.

2022-01-07 01:02 UTC, ChicagoDuan commented on redfish-core/lib/managers.hpp
> +                if (managerName != "bmc")
> Why was this check needed? Are there cases where we have multiple BMCs? Even if we do, wouldn't the LED associations take care of getting to the right LED?

I considered the situation of multiple Managers. If there is no such situation, I will modify it.

2022-01-12 14:03 UTC, gtmills commented
jenkins run tests please

2022-01-13 05:47 UTC, jinuthomas approved these changes

2022-01-13 05:47 UTC, jinuthomas approved these changes
looks good to me , will wait for the others to also go through this

2022-01-17 09:49 UTC, lxwinspur approved these changes

2022-01-19 01:51 UTC, ChicagoDuan commented
> @ChicagoDuan : Could you send this upstream too? I see https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43179, but that implementation is quite different

Sure

2022-01-19 03:44 UTC, gtmills approved these changes
Going to default some to Santosh / Jinu here. Looks fine.

2022-01-19 10:43 UTC, ChicagoDuan commented
> @ChicagoDuan : Could you send this upstream too? I see https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/43179, but that implementation is quite different

Done : https://gerrit.openbmc-project.xyz/c/openbmc/bmcweb/+/50494

2022-01-19 16:45 UTC, merged