Disallow disabling the service user
ibm-openbmc/bmcweb pull request #409
Opened 2022-06-29 23:00 UTC by joseph-reynolds

This changes the PATCH /redfish/v1/AccountService/Accounts/service operation so the service user cannot be disabled.  Effectively, the way to disable service user login is to delete the ACF file.

Tested: Yes

Signed-off-by: Joseph Reynolds <joseph-reynolds@charter.net>

2022-06-30 15:54 UTC, joseph-reynolds commented
Maybe this is not needed.  Meaning a BMC admin should be allowed to disable the service account login.

2022-07-05 17:09 UTC, gtmills commented
> Maybe this is not needed. Meaning a BMC admin should be allowed to disable the service account login.

I think a BMC admin should be able to disable the service account.

2022-07-05 17:10 UTC, gtmills requested changes
What defect is this? I don't agree with this change here (I could be convinced) but overall this needs more discussion.

2022-09-13 18:08 UTC, gtmills commented
Can we close or is this still needed?

2023-01-06 22:30 UTC, joseph-reynolds commented
Closing.

2023-01-06 22:30 UTC, closed without merging