Implement pcieslots LocationIndicatorActive
ibm-openbmc/bmcweb pull request #530
Opened 2023-02-06 09:18 UTC by ChicagoDuan

2023-02-06 15:19 UTC, baemyung reviewed
@ChicagoDuan 

I see slotType as "xyz.openbmc_project.Inventory.Item.PCIeSlot.SlotTypes.Unknown" from the system. 

In this case, dbusSlotTypeToRf() will return as "Invalid" even if *slotType is not empty.
```
        pcie_slots::SlotTypes redfishSlotType = dbusSlotTypeToRf(*slotType);
        if (slotType->empty())
```

Should dbusSlotTypeToRf() be written/returning as std::optional<>() so that we can check 'redfishSlotType' rather than the input '*slotType'?

Please take a look at https://github.com/ibm-openbmc/bmcweb/pull/529 ?


```
inline std::optional<pcie_slots::SlotTypes>
    dbusSlotTypeToRf(const std::string& slotType)
{
...
+    if (slotType.empty() ||
+        slotType ==
+            "xyz.openbmc_project.Inventory.Item.PCIeSlot.SlotTypes.Unknown")
+    {
+        return pcie_slots::SlotTypes::Invalid;
     }
+    // Unspecified slotType needs return an internal error.
+    return std::nullopt;
}
And then
redfish-core/lib/pcie_slots.hpp:

+        std::optional<pcie_slots::SlotTypes> redfishSlotType =
+            dbusSlotTypeToRf(*slotType);
+        if (!redfishSlotType)
         {
             messages::internalError(asyncResp->res);
             return;
         }
 ```

2023-02-07 01:34 UTC, baemyung commented
jenkins run tests please

2023-02-07 01:34 UTC, baemyung commented
jenkins run tests please

2023-02-07 06:16 UTC, ChicagoDuan commented
> @ChicagoDuan
> 
> I see slotType as "xyz.openbmc_project.Inventory.Item.PCIeSlot.SlotTypes.Unknown" from the system.
> 
> In this case, dbusSlotTypeToRf() will return as "Invalid" even if *slotType is not empty.
> 
> ```
>         pcie_slots::SlotTypes redfishSlotType = dbusSlotTypeToRf(*slotType);
>         if (slotType->empty())
> ```
> 
> Should dbusSlotTypeToRf() be written/returning as std::optional<>() so that we can check 'redfishSlotType' rather than the input '*slotType'?
> 
> Please take a look at #529 ?
> 
> ```
> inline std::optional<pcie_slots::SlotTypes>
>     dbusSlotTypeToRf(const std::string& slotType)
> {
> ...
> +    if (slotType.empty() ||
> +        slotType ==
> +            "xyz.openbmc_project.Inventory.Item.PCIeSlot.SlotTypes.Unknown")
> +    {
> +        return pcie_slots::SlotTypes::Invalid;
>      }
> +    // Unspecified slotType needs return an internal error.
> +    return std::nullopt;
> }
> And then
> redfish-core/lib/pcie_slots.hpp:
> 
> +        std::optional<pcie_slots::SlotTypes> redfishSlotType =
> +            dbusSlotTypeToRf(*slotType);
> +        if (!redfishSlotType)
>          {
>              messages::internalError(asyncResp->res);
>              return;
>          }
> ```

Done

2023-02-07 13:39 UTC, baemyung approved these changes
@ChicagoDuan 
PCIeSlots schema is currently disabled in upstream bmcweb (https://github.com/openbmc/bmcweb) by https://github.com/openbmc/bmcweb/commit/e825cbc8f967e54dfd6d911ebbbc6b2bfc7bc543.

Would you push this PCIeSlots schema and LocationIndicatorActive/PCIeSlots to upstream?

2023-02-07 14:13 UTC, baemyung requested changes
In case the slotType is "Unknown", it gives like

```

 curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots",
  "@odata.type": "#PCIeSlots.v1_4_1.PCIeSlots",
  "Id": "1",
  "Name": "PCIe Slot Information",
  "Slots": [
    {
      "HotPluggable": false,
      "Lanes": 0,
      "LocationIndicatorActive": null,      <====
      "PCIeType": "Invalid",    <====
      "SlotType": "U2"
    },
    {
      "HotPluggable": false,
      "Lanes": 0,
      "LocationIndicatorActive": null,
      "PCIeType": "Invalid",
      "SlotType": "U2"
    },
```

This is because this part of code does not handle the case of 'Invalid' properly.
(Note I'm following the code in ibm-public/openbmc/bmcweb 1030).

        std::optional<pcie_slots::SlotTypes> redfishSlotType =
            dbusSlotTypeToRf(*slotType);
        if (!redfishSlotType)
        {
            messages::internalError(asyncResp->res);
            return;
        }

This would need to be changed like

```
        std::optional<pcie_slots::SlotTypes> redfishSlotType =
            dbusSlotTypeToRf(*slotType);
        if (!redfishSlotType)
        {
            messages::internalError(asyncResp->res);
            return;
        }
        if (*redfishSlotType != pcie_slots::SlotTypes::Invalid)
        {
            slot["SlotType"] = *redfishSlotType;
        }
```

Similarly, pcieType would also be the case

```
        std::optional<pcie_device::PCIeTypes> pcieType =
            redfishPcieGenerationFromDbus(*generation);
        if (!pcieType)
        {
            messages::internalError(asyncResp->res);
            return;
        }
        slot["PCIeType"] = *pcieType;
    }
```

==>

```
       std::optional<pcie_device::PCIeTypes> pcieType =
            redfishPcieGenerationFromDbus(*generation);
        if (!pcieType)
        {
            messages::internalError(asyncResp->res);
            return;
        }
        if (*pcieType != pcie_device::PCIeTypes::Invalid)
        {
            slot["PCIeType"] = !pcieType;
        } 
    }
```

2023-02-07 14:45 UTC, baemyung reviewed
In addition, it would be better to add some details into debug traces.

```
(2023-02-07 14:29:34) [DEBUG "pcie_slots.hpp":323] Get properties for PCIeSlots associated to chassis = chassis
(2023-02-07 14:29:34) [DEBUG "led.hpp":240] Get LocationIndicatorActive
(2023-02-07 14:29:34) [DEBUG "led.hpp":240] Get LocationIndicatorActive
(2023-02-07 14:29:34) [DEBUG "led.hpp":240] Get LocationIndicatorActive
(2023-02-07 14:29:34) [DEBUG "led.hpp":240] Get LocationIndicatorActive
...
```

What if we add 'objPath' into DEBUG traces?

```
inline void
    getLocationIndicatorActive(const std::shared_ptr<bmcweb::AsyncResp>& aResp,
                               const std::string& objPath,
                               nlohmann::json& jsonInput)
{
    BMCWEB_LOG_DEBUG << "Get LocationIndicatorActive";
==>
   BMCWEB_LOG_DEBUG << "Get LocationIndicatorActive for " << objPath;
...
```

2023-02-07 15:31 UTC, baemyung commented
@ChicagoDuan 
As for the comparison, I took the output from 1030-ghe.

```
% curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots",
  "@odata.type": "#PCIeSlots.v1_5_0.PCIeSlots",
  "Id": "PCIeSlots",
  "Name": "PCIe Slot Information",
  "Slots": [
    {
      "HotPluggable": false,
      "Lanes": 0,
   ...
      "LocationIndicatorActive": false,   <=== THIS SEEMS different in 1050 - as it shows as "null"
   ...
      "SlotType": "U2"  <===
    },
```

No "PCIeType" as it is unknown.
However, LocationIndicatorActive is different between 1030 & 1050.

2023-02-08 01:20 UTC, lxwinspur commented
> @ChicagoDuan PCIeSlots schema is currently disabled in upstream bmcweb (https://github.com/openbmc/bmcweb) by [openbmc/bmcweb@e825cbc](https://github.com/openbmc/bmcweb/commit/e825cbc8f967e54dfd6d911ebbbc6b2bfc7bc543).
> 
> Would you push this PCIeSlots schema and LocationIndicatorActive/PCIeSlots to upstream?

@baemyung 
I pushed a new patch upstream, could you please review it?
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/60582

2023-02-08 11:21 UTC, baemyung commented
@ChicagoDuan @lxwinspur 

It looks like the new code seems for "slotType", but I still have a few questions.

1) How should we handle pcieType is empty() or  "xyz.openbmc_project.Inventory.Item.PCIeSlot.Generations.Unknown"?
In 1030, they are ignored, but in 1050/upstream, it is going to be set as "invalid"  in "pcie_slots.hpp" (although "pcie.hpp" is good).

1050/upstream:

./redfish-core/lib/pcie_slots.hpp:

```
   if (generation != nullptr)
    {
        std::optional<pcie_device::PCIeTypes> pcieType =
            redfishPcieGenerationFromDbus(*generation);
        if (!pcieType)
        {
            messages::internalError(asyncResp->res);
            return;
        }
==> It will set as "Invalid" if  pcieType is "xyz.openbmc_project.Inventory.Item.PCIeSlot.Generations.Unknown"
        slot["PCIeType"] = *pcieType;
    }
```

Should change redfishPcieGenerationFromDbus() to return as "nullopt" instead of "invalid"?

```
--- a/redfish-core/lib/pcie.hpp
+++ b/redfish-core/lib/pcie.hpp
@@ -140,12 +140,6 @@ inline std::optional<pcie_device::PCIeTypes>
     {
         return pcie_device::PCIeTypes::Gen5;
     }
-    if (generationInUse.empty() ||
-        generationInUse ==
-            "xyz.openbmc_project.Inventory.Item.PCIeSlot.Generations.Unknown")
-    {
-        return pcie_device::PCIeTypes::Invalid;
-    }

     // The value is not unknown or Gen1-5, need return an internal error.
     return std::nullopt;
```

OR check it in pcie_slots.hpp

```
--- a/redfish-core/lib/pcie_slots.hpp
+++ b/redfish-core/lib/pcie_slots.hpp
@@ -206,7 +206,10 @@ inline void
             messages::internalError(asyncResp->res);
             return;
         }
-        slot["PCIeType"] = *pcieType;
+        if (*pcieType != pcie_device::PCIeTypes::Invalid)
+        {
+            slot["PCIeType"] = *pcieType;
+        }
     }
```

2023-02-08 11:28 UTC, baemyung commented
2. Similarly, redfishSlotType has the same issue.

In case slotType is Unknown, dbusSlotTypeToRf() returns pcie_slots::SlotTypes::Invalid.

pcie_slots.hpp will set as "Invalid" if slotType is unknown.
This is different from 1030 (which ignores the "Unknown" case).

```
    if (slotType != nullptr)
    {
        std::optional<pcie_slots::SlotTypes> redfishSlotType =
            dbusSlotTypeToRf(*slotType);
        if (!redfishSlotType)
        {
            messages::internalError(asyncResp->res);
            return;
        }
==> It will set as "Invalid" if slotType is "unknown".
        slot["SlotType"] = *redfishSlotType;
    }
```

Similar to slotType, should we change dbusSlotTypeToRf() not to detect Unknown?
This way, the code (1050/upstream) will become consistent with 1030.

```
--- a/redfish-core/lib/pcie_slots.hpp
+++ b/redfish-core/lib/pcie_slots.hpp
@@ -61,12 +61,6 @@ inline std::optional<pcie_slots::SlotTypes>
     {
         return pcie_slots::SlotTypes::U2;
     }
-    if (slotType.empty() ||
-        slotType ==
-            "xyz.openbmc_project.Inventory.Item.PCIeSlot.SlotTypes.Unknown")
-    {
-        return pcie_slots::SlotTypes::Invalid;
-    }

     // Unspecified slotType needs return an internal error.
     return std::nullopt;
```

2023-02-08 11:32 UTC, baemyung requested changes
Lastly, 

3) as I reported previously, I'm seeing "LocationIndicatorActive" as "null" instead of "false".
Could you investigate this and fix?

```
 curl -k -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots",
  "@odata.type": "#PCIeSlots.v1_4_1.PCIeSlots",
  "Id": "1",
  "Name": "PCIe Slot Information",
  "Slots": [
    {
      "HotPluggable": false,
      "Lanes": 0,
      "LocationIndicatorActive": null,      <==== this should "false"
      "PCIeType": "Invalid",                       <==== This entry should be off from the output
      "SlotType": "U2"
    },
    {
      "HotPluggable": false,
      "Lanes": 0,
      "LocationIndicatorActive": null,  <==== this should "false"
      "PCIeType": "Invalid",                  <==== This entry should be off from the output
      "SlotType": "U2"
    },
```

2023-02-09 08:12 UTC, ChicagoDuan commented
> @ChicagoDuan @lxwinspur
> 
> I have posted 3 points.
> 
> 1. pcieType handling - suggest to change redfishPcieGenerationFromDbus() to ignore Unknown
> 2. slotType handling - suggest to change dbusSlotTypeToRf() to ignore Unknown
> 3. LocationIndicatorActive - is showing "null" instead of "false".
> 
> Please address those points or provide explanations. Thanks

Okay, I'll fix them.

2023-02-09 09:55 UTC, ChicagoDuan commented
> 3. LocationIndicatorActive - is showing "null" instead of "false".

Hi @baemyung
When we can‘t get the status of LocationIndicatorActive from D-BUS, the value here is “null”.  I guess you may not have successfully obtained the LocationIndicatorActive value from D-BUS.

2023-02-09 12:27 UTC, baemyung commented
@ChicagoDuan @lxwinspur 
It looks like (1) & (2) are addressed.  I'll verify it.

Regarding (3),  for the comparison, the result is different from 1030 firmware on the same machine.

Could you show the test procedure as you've done like https://github.com/ibm-openbmc/bmcweb/commit/9fff1194c0f39e297a231cab42ef6729b8e8e78b?

2023-02-09 13:25 UTC, baemyung requested changes
This is my test result using this code.

```
%
curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots",
  "@odata.type": "#PCIeSlots.v1_4_1.PCIeSlots",
  "Id": "1",
  "Name": "PCIe Slot Information",
  "Slots": [
    {
      "HotPluggable": false,
      "Lanes": 0,
      "LocationIndicatorActive": null,
      "PCIeType": "Invalid",
      "SlotType": "U2"
    },
......
}

```

Now I tried to change 
```
% curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{"LocationIndicatorActive":true},{"LocationIndicatorActive":true}]}' https://${bmc}:18080/redfish/v1/Chassis/chassis/PCIeSlots

{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.13.0.InternalError",
        "MessageSeverity": "Critical",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service."
      },
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.13.0.InternalError",
        "MessageSeverity": "Critical",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service."

...

```

BMCWEB debug log says:

```
(2023-02-09 13:20:02) [DEBUG "query.hpp":114] setup redfish route
(2023-02-09 13:20:02) [DEBUG "chassis_utils.hpp":18] checkChassisId enter
(2023-02-09 13:20:02) [DEBUG "chassis_utils.hpp":63] checkChassisId exit
(2023-02-09 13:20:02) [DEBUG "chassis_utils.hpp":28] getValidChassisPath respHandler enter
(2023-02-09 13:20:02) [DEBUG "pcie_slots.hpp":87] Check PCIeSlots count for PCIeSlots request associated to chassis
(2023-02-09 13:20:02) [ERROR "pcie_slots.hpp":130] The actual number of cpieslots is greater than total
(2023-02-09 13:20:02) [CRITICAL "error_messages.cpp":258] Internal Error ../../../../../../../../../bmcweb/redfish-core/lib/pcie_slots.hpp(132:44) `redfish::checkPCIeSlotsCount(const std::shared_ptr<bmcweb::AsyncResp>&, unsigned int, const std::string&, std::function<void(const std::map<unsigned int, std::__cxx11::basic_string<char> >&)>&&)::<lambda(boost::system::error_code, const dbus::utility::MapperGetSubTreePathsResponse&)>::<lambda(const boost::system::error_code&, const dbus::utility::MapperEndPoints&)>`:
(2023-02-09 13:20:02) [ERROR "pcie_slots.hpp":130] The actual number of cpieslots is greater than total
(2023-02-09 13:20:02) [CRITICAL "error_messages.cpp":258] Internal Error ../../../../../../../../../bmcweb/redfish-core/lib/pcie_slots.hpp(132:44) `redfish::checkPCIeSlotsCount(const std::shared_ptr<bmcweb::AsyncResp>&, unsigned int, const std::string&, std::function<void(const std::map<unsigned int, std::__cxx11::basic_string<char> >&)>&&)::<lambda(boost::system::error_code, const dbus::utility::MapperGetSubTreePathsResponse&)>::<lambda(const boost::system::error_code&, const dbus::utility::MapperEndPoints&)>`:
(2023-02-09 13:20:02) [ERROR "pcie_slots.hpp":130] The actual number of cpieslots is greater than total

```

2023-02-09 13:27 UTC, lxwinspur commented
> @ChicagoDuan @lxwinspur It looks like (1) & (2) are addressed. I'll verify it.
> 
> Regarding (3), for the comparison, the result is different from 1030 firmware on the same machine.
> 
> Could you show the test procedure as you've done like [9fff119](https://github.com/ibm-openbmc/bmcweb/commit/9fff1194c0f39e297a231cab42ef6729b8e8e78b)?

@baemyung 
Note: we need to update associations.json and add the object path of pckeslot, like this:
```
    {
        "path": "system/chassis/motherboard/pcieslot0",
        "endpoints": [
            {
                "types": {
                    "rType": "inventory",
                    "fType": "chassis"
                },
                "paths": [
                    "/xyz/openbmc_project/inventory/system/chassis"
                ]
            },
            {
                "types": {
                    "rType": "identified_by",
                    "fType": "identifying"
                },
                "paths": [
                    "/xyz/openbmc_project/led/groups/xxx"
                ]
            }
        ]
    }
```

2023-02-09 13:55 UTC, baemyung commented
> 

Which previous commit / PR (in 1030) changed this association?
Should this PR also contain the association change to make sure/verify this PR is working correctly?
In other words, without association change, this PR does not work and thus this can't be merged.

2023-02-09 14:41 UTC, gtmills commented
For next time, please fill out the PR msg, including the upstream commits that are being picked up

2023-02-09 14:45 UTC, baemyung commented
@ChicagoDuan @lxwinspur 
I've compared those recipe files between 1030 & 1050 - 
 - `openbmc/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/associations.json`
and the other p10bmc related files.

However, they are mostly the same, and I don't see something related to what you showed.

Could you take a look at them, and add/update those files if you see something missing?

2023-02-09 14:51 UTC, baemyung commented
In fact, it is in association file for everest & rainer.

For example,

`openbmc/meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager/p10bmc/ibm,everest_associations.json`

```
       {
            "path": "system/chassis/motherboard/pcieslot2",
            "endpoints":
            [
                {
                    "types":
                    {
                        "rType": "fault_inventory_object",
                        "fType": "fault_led_group"
                    },
                    "paths":
                    [
                        "/xyz/openbmc_project/led/groups/pcieslot_c02_fault"
                    ]
                },
                {
                    "types":
                    {
                        "rType": "identify_inventory_object",
                        "fType": "identify_led_group"
                    },
                    "paths":
                    [
                        "/xyz/openbmc_project/led/groups/pcieslot_c02_identify"
                    ]
                }
            ]
        },
```

Then, the issue may be at somewhere else.

2023-02-09 16:14 UTC, baemyung commented
Looking at the point (1) & (2), they are still incorrect.

-   *generation is "xyz.openbmc_project.Inventory.Item.PCIeSlot.Generations.Unknown, it will set as "Invalid" rather than ignoring.
- similarly, slotType is "xyz.openbmc_project.Inventory.Item.PCIeSlot.SlotTypes.Unknown", it will also set as "Invalid" instead of ignoring.


In both pcieType and slotType needs to check "Invalid" case and ignore them.
Otherwise, the output will show "Invalid" instead of not showing it.

```
inline std::optional<pcie_slots::SlotTypes>
    dbusSlotTypeToRf(const std::string& slotType)
{
...
+    if (slotType.empty() ||
+        slotType ==
+            "xyz.openbmc_project.Inventory.Item.PCIeSlot.SlotTypes.Unknown")
+    {
+        return pcie_slots::SlotTypes::Invalid;
     }
+    // Unspecified slotType needs return an internal error.
+    return std::nullopt;
}

And then
redfish-core/lib/pcie_slots.hpp:

        std::optional<pcie_slots::SlotTypes> redfishSlotType =
            dbusSlotTypeToRf(*slotType);
        if (!redfishSlotType)
        {
            messages::internalError(asyncResp->res);
            return;
        }
+        if (*redfishSlotType != pcie_slots::SlotTypes::Invalid)
+        {
            slot["SlotType"] = *redfishSlotType;
        }
```

Similarly, the same approach needs to be done for pcieType.

2023-02-09 19:54 UTC, baemyung requested changes
@ChicagoDuan @lxwinspur 

The reason why we get "LocationIndicatorActive = null" is because the code is using different object path.

This PR code is using
   branch    List, create, or delete branches

` [DEBUG "led.hpp":260] Get LocationIndicatorActive objPath=/xyz/openbmc_project/inventory/system/chassis/motherboard/pcieslot1/identifying
`

However, the system's assosication is "/identify_led_group" like
`/xyz/openbmc_project/inventory/system/chassis/motherboard/pcieslot1/identify_led_group
`

So, the  fix for getLocationIndicatorActive() would be

```
diff --git a/redfish-core/lib/led.hpp b/redfish-core/lib/led.hpp
index bf3924f4..9147b7e6 100644
--- a/redfish-core/lib/led.hpp
+++ b/redfish-core/lib/led.hpp
@@ -241,7 +241,7 @@ inline void

     nlohmann::json& jsonIn = jsonInput["LocationIndicatorActive"];
     dbus::utility::getAssociationEndPoints(
-        objPath + "/identifying",
+        objPath + "/identify_led_group",
         [aResp, &jsonIn](const boost::system::error_code& ec,
                          const dbus::utility::MapperEndPoints& endpoints) {
         if (ec)
@@ -283,7 +283,7 @@ inline void
     BMCWEB_LOG_DEBUG << "Set LocationIndicatorActive";

     dbus::utility::getAssociationEndPoints(
-        objPath + "/identifying",
+        objPath + "/identify_led_group",
         [aResp, ledState](const boost::system::error_code& ec,
                           const dbus::utility::MapperEndPoints& endpoints) {
         if (ec)
```


However,  PATCH part is still causing the error.

% curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{"LocationIndicatorActive":true},{"LocationIndicatorActive":true}]}' https://${bmc}:18080/redfish/v1/Chassis/chassis/PCIeSlots

2023-02-10 01:28 UTC, baemyung commented
PATCH error is caused by the mismatch of the view of 'total' and 'updatePcieSlotsMaps.size()'.
total is the number of input but updatePcieSlotsMaps.size() can be essentially pcieSlotsPaths.size().  

Therefore, this would always trigger
 ` if (updatePcieSlotsMaps.size() > total)`
  
This can be verified by adding some debug traces.

```

(2023-02-09 21:44:03) [INFO "pcie_slots.hpp":125]  TEST: endpoint match: endpoint=/xyz/openbmc_project/inventory/system/chassis, updatePcieSlotsMaps[index=2]=path=/xyz/openbmc_project/inventory/system/chassis/motherboard/dasd_backplane/nvme1, slotNum=22, count=2
(2023-02-09 21:44:03) [INFO "pcie_slots.hpp":129]   TEST: total=1 updatePcieSlotsMaps.size=2
(2023-02-09 21:44:03) [ERROR "pcie_slots.hpp":133] The actual number of cpieslots 2 is greater than total=1
(2023-02-09 21:44:03) [CRITICAL "error_messages.cpp":258] Internal Error ../../../../../../../../../ibm-bmcweb/redfish-core/lib/pcie_slots.hpp(135:44) `redfish::checkPCIeSlotsCount(const std::shared_ptr<bmcweb::AsyncResp>&, unsigned int, const std::string&, std::function<void(const std::map<unsigned int, std::__cxx11::basic_string<char> >&)>&&)::<lambda(boost::system::error_code, const dbus::utility::MapperGetSubTreePathsResponse&)>::<lambda(const boost::system::error_code&, const dbus::utility::MapperEndPoints&)>`:

````

Anyway, 
I submitted the new PR https://github.com/ibm-openbmc/bmcweb/pull/543 which should cover the issues.

So, we can close this PR #530, and move to PR #543.
Please review https://github.com/ibm-openbmc/bmcweb/pull/543.

2023-02-10 01:41 UTC, baemyung commented
Since it is move to #543, let's close this PR.

2023-02-10 01:41 UTC, closed without merging

2023-02-10 01:41 UTC, ChicagoDuan commented
>  total is the number of input but updatePcieSlotsMaps.size() can be essentially pcieSlotsPaths.size().

Hi @baemyung,  we need updatePcieSlotsMaps.size() = total  ,  Please see :  https://github.com/ibm-openbmc/bmcweb/pull/530/commits/254ce5388ad86a17e6e79d9c49a7059154164a24
"We need to set the LocationIndicatorActive of all the slots in the dopatch command, even if we only want to modify one of them.(ex: see the second test result)"

2023-02-10 01:59 UTC, baemyung commented
Please test and verify it on the actual machine.

This code makes updatePcieSlotsMaps[] to grow upto pcieSlotsPaths.size(), not toal (i.e. # of input array).

```
         auto slotNum = pcieSlotsPaths.size();
104         for (const auto& path : pcieSlotsPaths)
105         {
106             index++;
...
122                 for (const auto& endpoint : endpoints)
123                 {
124                     if (endpoint == validChassisPath)
125                     {
126                         updatePcieSlotsMaps[index] = path;
127                     }
128                 }
```


As the result, it always hit this part.
```
                 if (updatePcieSlotsMaps.size() > slotNum)
131                 {
132                     BMCWEB_LOG_ERROR
133                         << "The actual number of cpieslots is greater than slotNum";
134                     messages::internalError(asyncResp->res);
135                 }
```

In 1030, it goes thru subtree, and the code compares 'index' (which is a matching count [not like 1050]) and 'total'.
This will be correct as 'matching entry count' will be the same as input count.

However,   1050 uses getAssociation() and it builds up updatePcieSlotsMaps[] which grows up topcieSlotsPaths.size() and compare it with 'total'.

Since I already generate a new PR #543 which is verified, could we move to it and review more there?

2023-02-10 02:13 UTC, ChicagoDuan commented
We have done the test. Can you post the complete results of the following commands ：
`curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots`
I want to know how many slots you can get using the above command.

Can we communicate on discord? What is your discord id?

2023-02-10 02:28 UTC, ChicagoDuan commented
For example, If you can get 4 slots(use this command: `curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots`).  
You want to set LocationIndicatorActive of the second slot to true. You should send this command:
```
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true},{},{}]}' 
 https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
```

2023-02-10 03:42 UTC, baemyung commented
I don't know how the test was succeeded - esp on p10 machines (e.g. everest or rainer - which was used for 1030).
Perhaps, could you show what you've done - command and its output?

As shown above, with your code, 

1) GET did not work correctly.

```
% curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
  "@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots",
  "@odata.type": "#PCIeSlots.v1_4_1.PCIeSlots",
  "Id": "1",
  "Name": "PCIe Slot Information",
  "Slots": [
    {
      "HotPluggable": false,
      "Lanes": 0,
      "LocationIndicatorActive": null,  <======= THIS IS INCORRECT
      "PCIeType": "Invalid",                  <======= THIS IS INCORRECT
      "SlotType": "U2"
    },
    {
      "HotPluggable": false,
      "Lanes": 0,
      "LocationIndicatorActive": null,
      "PCIeType": "Invalid",
      "SlotType": "U2"
    },
    {
      "HotPluggable": false,
      "Lanes": 0,
      "LocationIndicatorActive": null,
      "PCIeType": "Invalid",
      "SlotType": "U2"
    },
....
```

The reasons are because
(1) missing logic

```
        if (*redfishSlotType != pcie_slots::SlotTypes::Invalid)
        {
            slot["SlotType"] = *redfishSlotType;
        }
```

(2) dbus name is incorrect

```
    getLocationIndicatorActive(const std::shared_ptr<bmcweb::AsyncResp>& aResp,
                               const std::string& objPath,
                               nlohmann::json& jsonInput)
{
    BMCWEB_LOG_DEBUG << "Get LocationIndicatorActive";

    nlohmann::json& jsonIn = jsonInput["LocationIndicatorActive"];
    dbus::utility::getAssociationEndPoints(
        objPath + "/identifying",     <======== THIS SHOULD BE "/identify_led_group".  This is even different from 1030.
        [aResp, &jsonIn](const boost::system::error_code& ec,
                         const dbus::utility::MapperEndPoints& endpoints) {
```

2) PATCH is even worse.

```
% curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{"LocationIndicatorActive":true},{"LocationIndicatorActive":false},{"LocationIndicatorActive":true}]}' https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.13.0.InternalError",
        "MessageSeverity": "Critical",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service."
      },
      {
        "@odata.type": "#Message.v1_1_1.Message",
        "Message": "The request failed due to an internal service error.  The service is still operational.",
        "MessageArgs": [],
        "MessageId": "Base.1.13.0.InternalError",
        "MessageSeverity": "Critical",
        "Resolution": "Resubmit the request.  If the problem persists, consider resetting the service."
      },
....<repeating for all slots>....
}
```

At the time,  BMCWEB deug log shows that
```
2023-02-10 03:26:09) [DEBUG "pcie_slots.hpp":87] Check PCIeSlots count for PCIeSlots request associated to chassis
(2023-02-10 03:26:09) [ERROR "pcie_slots.hpp":130] The actual number of cpieslots is greater than total
(2023-02-10 03:26:09) [CRITICAL "error_messages.cpp":258] Internal Error ../../../../../../../../../bmcweb/redfish-core/lib/pcie_slots.hpp(132:44) `redfish::checkPCIeSlotsCount(const std::shared_ptr<bmcweb::AsyncResp>&, unsigned int, const std::string&, std::function<void(const std::map<unsigned int, std::__cxx11::basic_string<char> >&)>&&)::<lambda(boost::system::error_code, const dbus::utility::MapperGetSubTreePathsResponse&)>::<lambda(const boost::system::error_code&, const dbus::utility::MapperEndPoints&)>`:
(2023-02-10 03:26:09) [ERROR "pcie_slots.hpp":130] The actual number of cpieslots is greater than total
(2023-02-10 03:26:09) [CRITICAL "error_messages.cpp":258] Internal Error ../../../../../../../../../bmcweb/redfish-core/lib/pcie_slots.hpp(132:44) `redfish::checkPCIeSlotsCount(const std::shared_ptr<bmcweb::AsyncResp>&, unsigned int, const std::string&, std::function<void(const std::map<unsigned int, std::__cxx11::basic_string<char> >&)>&&)::<lambda(boost::system::error_code, const dbus::utility::MapperGetSubTreePathsResponse&)>::<lambda(const boost::system::error_code&, const dbus::utility::MapperEndPoints&)>`:
(2023-02-10 03:26:09) [ERROR "pcie_slots.hpp":130] The actual number of cpieslots is greater than total
```

As I also showed after adding more debug traces, it is like

```

(2023-02-09 21:44:03) [INFO "pcie_slots.hpp":125]  TEST: endpoint match: endpoint=/xyz/openbmc_project/inventory/system/chassis, updatePcieSlotsMaps[index=2]=path=/xyz/openbmc_project/inventory/system/chassis/motherboard/dasd_backplane/nvme1, slotNum=22, count=2
(2023-02-09 21:44:03) [INFO "pcie_slots.hpp":129]   TEST: total=1 updatePcieSlotsMaps.size=2
(2023-02-09 21:44:03) [ERROR "pcie_slots.hpp":133] The actual number of cpieslots 2 is greater than total=1
(2023-02-09 21:44:03) [CRITICAL "error_messages.cpp":258] Internal Error ../../../../../../../../../ibm-bmcweb/redfish-core/lib/pcie_slots.hpp(135:44) `redfish::checkPCIeSlotsCount(const std::shared_ptr<bmcweb::AsyncResp>&, unsigned int, const std::string&, std::function<void(const std::map<unsigned int, std::__cxx11::basic_string<char> >&)>&&)::<lambda(boost::system::error_code, const dbus::utility::MapperGetSubTreePathsResponse&)>::<lambda(const boost::system::error_code&, const dbus::utility::MapperEndPoints&)>`:
.....

(2023-02-09 21:44:03) [CRITICAL "error_messages.cpp":258] Internal Error ../../../../../../../../../ibm-bmcweb/redfish-core/lib/pcie_slots.hpp(135:44) `redfish::checkPCIeSlotsCount(const std::shared_ptr<bmcweb::AsyncResp>&, unsigned int, const std::string&, std::function<void(const std::map<unsigned int, std::__cxx11::basic_string<char> >&)>&&)::<lambda(boost::system::error_code, const dbus::utility::MapperGetSubTreePathsResponse&)>::<lambda(const boost::system::error_code&, const dbus::utility::MapperEndPoints&)>`:
(2023-02-09 21:44:03) [INFO "pcie_slots.hpp":140]   TEST: TODO -- CALLBACK?? count==slotNum=22, size()=21, total=1
(2023-02-09 21:44:03) [CRITICAL "error_messages.cpp":258] Internal Error ../../../../../../../../../ibm-bmcweb/redfish-core/lib/pcie_slots.hpp(148:48) `redfish::checkPCIeSlotsCount(const std::shared_ptr<bmcweb::AsyncResp>&, unsigned int, const std::string&, std::function<void(const std::map<unsigned int, std::__cxx11::basic_string<char> >&)>&&)::<lambda(boost::system::error_code, const dbus::utility::MapperGetSubTreePathsResponse&)>::<lambda(const boost::system::error_code&, const dbus::utility::MapperEndPoints&)>`:




```

2023-02-10 03:45 UTC, baemyung commented
> 
> This code makes updatePcieSlotsMaps[] to grow upto pcieSlotsPaths.size(), not toal (i.e. # of input array).
> 
> ```
>          auto slotNum = pcieSlotsPaths.size();
> 104         for (const auto& path : pcieSlotsPaths)
> 105         {
> 106             index++;
> ...
> 122                 for (const auto& endpoint : endpoints)
> 123                 {
> 124                     if (endpoint == validChassisPath)
> 125                     {
> 126                         updatePcieSlotsMaps[index] = path;
> 127                     }
> 128                 }
> ```
> 
> As the result, it always hit this part.
> 
> ```
>                  if (updatePcieSlotsMaps.size() > slotNum)
> 131                 {
> 132                     BMCWEB_LOG_ERROR
> 133                         << "The actual number of cpieslots is greater than slotNum";
> 134                     messages::internalError(asyncResp->res);
> 135                 }
> ```
> 
> In 1030, it goes thru subtree, and the code compares 'index' (which is a matching count [not like 1050]) and 'total'. This will be correct as 'matching entry count' will be the same as input count.
> 
> However, 1050 uses getAssociation() and it builds up updatePcieSlotsMaps[] which grows up topcieSlotsPaths.size() and compare it with 'total'.
> 


Please respond to this code explanation.
updatePcieSlotsMaps.size() can be bigger than total (which is fixed to the input count).

2023-02-10 03:51 UTC, baemyung commented
@ChicagoDuan 

1030 pcie_slots.hpp code logic is different from your 1050 code in dealing with index,count,total etc.
Please compare them again.

(Note that 1030 code does not use updatePcieSlotsMaps, but instead simply keeping track of index [which matches to input count].  In 1050, updatePcieSlotsMaps is built for all slots for the further usage.  This makes differences).

I would suggest - try it again on rainer/everest, and show your command and outputs.
Once we analyze the codes (esp between 1030 and 1050) and you collect the data, we can further discuss about the discrepancy.

2023-02-10 03:52 UTC, baemyung commented
My discord id is myungbae#7599.  (Not sure how I can be active on it)

2023-02-10 04:09 UTC, baemyung commented
@ChicagoDuan 

The key issue is at

```
      for (const auto& path : pcieSlotsPaths)
        {
            index++;
            dbus::utility::getAssociationEndPoints(
                path + "/chassis",
                [asyncResp, total, validChassisPath, count{++count}, slotNum,
                 index, path,
                 callback](const boost::system::error_code& ec1,
                           const dbus::utility::MapperEndPoints& endpoints) {
....
                for (const auto& endpoint : endpoints)
                {
                    if (endpoint == validChassisPath)
                    {
                        updatePcieSlotsMaps[index] = path;
                    }
                }

                if (updatePcieSlotsMaps.size() > total)    //<== "total" needs to be replaced with "slotNum"
                {
                    BMCWEB_LOG_ERROR
                        << "The actual number of cpieslots is greater than total";
                    messages::internalError(asyncResp->res);
                }

                if (count == slotNum)  //<== 'count'  is essentially same as 'index' as count keeps incrementing for each getAssociationEndPoints() call, and slotNum will be same as # of pcieslots.
                {
                    // Last time DBus has returned
                    if (updatePcieSlotsMaps.size() == total)   //<== This is also incorrect and redundant.
                    {
                        callback(updatePcieSlotsMaps);
                    }
                    else
                    {
                        messages::internalError(asyncResp->res);
                    }
                }
```

2023-02-10 06:04 UTC, ChicagoDuan commented
@baemyung 
About the PATCH error, your patch command is wrong. I see that you have more than three pcieslots, but there are only two pcieslots in your patch request(-X PATCH -d '{"Slots":[**{"LocationIndicatorActive":true},{"LocationIndicatorActive":true}**]}' ).  
You should write request like this: `-d '{"Slots":[{"LocationIndicatorActive":true},{"LocationIndicatorActive":true},{},{},{},{}......]}' `

Please read the commit message I posted to you carefully: 
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42216/19//COMMIT_MSG#13
https://gerrit.openbmc.org/c/openbmc/bmcweb/+/42216/19//COMMIT_MSG#83

2023-02-10 06:18 UTC, ChicagoDuan commented
**"We need to set the LocationIndicatorActive of all the slots in the
dopatch command, even if we only want to modify one of
them.(ex: see the second test result)"**

https://github.com/ibm-openbmc/bmcweb/pull/530#issuecomment-1425090851
https://github.com/ibm-openbmc/bmcweb/pull/530/commits/254ce5388ad86a17e6e79d9c49a7059154164a24

```
For example, If you can get 4 slots(use this command: curl -k -H "X-Auth-Token: $token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots).
You want to set LocationIndicatorActive of the second slot to true. You should send this command:
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true},{},{}]}' 
 https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
```
Do you understand my example? You can ask questions if you don't understand. If you understand, you can try PATCH in this way

2023-02-10 06:40 UTC, ChicagoDuan commented
> if (updatePcieSlotsMaps.size() > total)    //<== "total" needs to be replaced with "slotNum"

No, it is correct to use "total" here. Please see the description of the  checkPCIeSlotsCount() function：
```
// Check whether the total number of slots in the request is consistent with the
// actual total number of slots
void checkPCIeSlotsCount()
```

2023-02-10 13:52 UTC, baemyung commented
Ok, I can match them via #543.
As mentioned, it is not the only one to fix -- "null" and "invalid" output.

Second, 
What kind of the message should be printed if the count does not match?
If the input needs to match with the number of slots, such check can be done much upfront and return just one error instead of going all of the entries and check it at last?

On the other hand, 
I understand that the middle slot can be specified as {} if it does not need to change.
However, why would it require the tailing {} inputs?

For example, if some middle slots need to keep as they are, it makes sense to set as {}.

```
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true},{},{},{"LocationIndicatorActive":true}]}' 
 https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
```

However, if all of the tailing slots are not changing, it can be shortened without requiring {} at the end?

```
curl -k -H "X-Auth-Token: $token" -X PATCH -d '{"Slots":[{},{"LocationIndicatorActive":true},{},{}]}' 
 https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
```

2023-02-10 16:12 UTC, baemyung commented
@ChicagoDuan 
OR,
could you explain a good reason why/how the approach (1) [allowing less # of slot args] is not going to work?

2023-02-10 19:31 UTC, baemyung commented
@ChicagoDuan 

At this time, I'll keep the current logic (i.e., #inputs == #slots) for the code consistency and follow 1030-logic to deal with the error handling.

```
-- a/redfish-core/lib/pcie_slots.hpp
+++ b/redfish-core/lib/pcie_slots.hpp
@@ -112,10 +112,30 @@ void checkPCIeSlotsCount(
                            const dbus::utility::MapperEndPoints& endpoints) {
                 if (ec1)
                 {
-                    if (ec1.value() != EBADR)
+                    if (ec1.value() == EBADR)
                     {
-                        messages::internalError(asyncResp->res);
+                        if (count == slotNum)
+                        {
+                            // the total number of slots in the request
+                            // is correct
+                            if (updatePcieSlotsMaps.size() == total)
+                            {
+                                callback(updatePcieSlotsMaps);
+                            }
+                            else
+                            {
+                                messages::resourceNotFound(
+                                    asyncResp->res, "Chassis", "slots count");
+                                return;
+                            }
+                        }
+
+                        // This PCIeSlot have no chassis association.
+                        return;
                     }
+                    BMCWEB_LOG_ERROR << "DBUS response error";
+                    messages::internalError(asyncResp->res);
+
                     return;
                 }
```

This point about #inputs/#slots may be re-discussed later in the future.
I'll make the changes in #543.