Link Fabric adapter to PCIeDevice schema
ibm-openbmc/bmcweb pull request #583
Opened 2023-02-23 14:52 UTC by SunnySrivastava1984

This commit implement changes to populate link to PCIeDevice schema in case the given Fabric adapter also implements PCIeDevice interface.

Validator has been executed and no new error was found.

Sample Output:
{
  "@odata.id": "/redfish/v1/Systems/system/FabricAdapters/pcie_card8",
  "@odata.type": "#FabricAdapter.v1_4_0.FabricAdapter",
  "Id": "pcie_card8",
  "Links": {
    "PCIeDevices": [
      {
        "@odata.id": "/redfish/v1/Systems/system/PCIeDevices/pcie_card8"
      }
    ],
    "PCIeDevices@odata.count": 1
  },
  "Location": {
    "PartLocation": {
      "ServiceLabel": "U78DB.ND0.WZS000G-P0-C8"
    }
  },
  "Name": "Fabric Adapter",
  "Status": {
    "Health": "OK",
    "State": "Absent"
  }
}

2023-02-23 14:53 UTC, SunnySrivastava1984 commented
The change is very specific to PCIe Topology requirement, hence no commit upstream.

2023-02-23 20:52 UTC, gtmills commented
Going to default to @baemyung and @Lakshmi-y here

2023-02-23 21:29 UTC, baemyung approved these changes

2023-02-23 21:47 UTC, Lakshmi-y approved these changes

2023-02-23 21:54 UTC, Lakshmi-y requested changes
Upstream CI is going to fail, can you include the following 
#include <sdbusplus/message/native_types.hpp>

2023-02-24 03:53 UTC, SunnySrivastava1984 commented
> Upstream CI is going to fail, can you include the following #include <sdbusplus/message/native_types.hpp>

This is PCIe Topology specific code. I am not sure if we are going to take this upstream.
Also, Since CI is passing here, lets take the suggested change in the upstream patch set if we push it there.

2023-02-27 15:39 UTC, gtmills approved these changes

2023-03-01 16:14 UTC, merged