Bmcweb: Add PcieSlots Location Code
ibm-openbmc/bmcweb pull request #650
Opened 2023-03-31 18:20 UTC by Alpana07

Bmcweb: Add PcieSlots Location Code
    
    This commit fixes this STG Defect 478749.
    This commit adds location code for pcieSlots.
    Upstream commit- https://gerrit.openbmc.org/c/openbmc/bmcweb/+/62219
    
    Tested:
    -Ran Redfish service validator,
     No new error and can see the Location code for pcieSlots
    
    -Verified on Rainier100 system, Location code shows up for PCIeSlots.
    
    curl -k -H "X-Auth-Token: $bmc_token" -X GET https://${bmc}/redfish/v1/Chassis/chassis/PCIeSlots
    {
      "@odata.id": "/redfish/v1/Chassis/chassis/PCIeSlots",
      "@odata.type": "#PCIeSlots.v1_5_0.PCIeSlots",
      "Id": "1",
      "Name": "PCIe Slot Information",
      "Slots": [
        {
          "HotPluggable": false,
          "Lanes": 0,
          "Links": {
            "Oem": {
              "IBM": {
                "AssociatedAssembly": [
                  {
                    "@odata.id": "/redfish/v1/Chassis/chassis/Assembly#/Assemblies/19"
                  }
                ]
              }
            },
            "PCIeDevice": [
              {
                "@odata.id": "/redfish/v1/Systems/system/PCIeDevices/motherboard_disk_backplane0_nvme2_dp0_drive2"
              }
            ]
          },
          "Location": {
            "PartLocation": {
              "ServiceLabel": "U78DA.ND0.       -P1-C2"
            }
          },
          "LocationIndicatorActive": false,
          "Oem": {
            "@odata.type": "#OemPCIeSlots.Oem",
            "IBM": {
              "@odata.type": "#OemPCIeSlots.IBM",
              "LinkId": 0
            }
          },
          "SlotType": "U2"
        },
    
    Change-Id: I2bef85d9dbd95d5f0b923f5453c8cc72381ce546
    Signed-off-by: Alpana Kumari <alpankum@in.ibm.com>

2023-04-03 14:16 UTC, gtmills approved these changes

2023-04-05 04:26 UTC, SunnySrivastava1984 requested changes
I doubt this will work. Also the test result pasted is of PCIe Device, whereas the changes are in PCIe Slots.
Please verify.

2023-04-05 14:56 UTC, gtmills requested changes
Sunny had some doubts here.

2023-04-06 08:36 UTC, Alpana07 commented
Sunny's comments have been addressed.

2023-04-06 08:42 UTC, SunnySrivastava1984 commented on redfish-core/lib/pcie_slots.hpp
> +    sdbusplus::asio::getAllProperties(
Please use get property when you are fetching just one property.

sdbusplus::asio::getProperty\<std::string\> (
        *crow::connections::systemBus, serviceName, fabricAdapterPath,
        "xyz.openbmc_project.Inventory.Decorator.LocationCode", "LocationCode",
        [aResp](const boost::system::error_code ec,
                const std::string& property){}

2023-04-06 17:53 UTC, SunnySrivastava1984 requested changes

2023-04-06 17:53 UTC, SunnySrivastava1984 commented on redfish-core/lib/pcie_slots.hpp
> +    // Get and set the location code
Please add a function and move this code there.

2023-04-11 07:12 UTC, SunnySrivastava1984 requested changes

2023-04-11 07:12 UTC, SunnySrivastava1984 commented on redfish-core/lib/pcie_slots.hpp
> +inline void setLC(const std::shared_ptr<bmcweb::AsyncResp>& asyncResp,
Please have a proper readable name.
getLocationCode?

2023-04-11 12:41 UTC, gtmills commented on redfish-core/lib/pcie_slots.hpp
> +            BMCWEB_LOG_ERROR << "PcieSlot location code value is empty ";
probably shouldn't be a LOG_ERROR if we aren't throwing an error. I guess oh well. WARNING makes more sense.

2023-04-12 15:23 UTC, jinuthomas approved these changes

2023-04-13 18:57 UTC, gtmills commented on redfish-core/lib/pcie_slots.hpp
> +        if (property.empty())
Still unresolved comment

2023-04-14 16:35 UTC, gtmills commented on redfish-core/lib/pcie_slots.hpp
> +        if (property.empty())
Why do we need this check?

2023-04-14 17:59 UTC, Alpana07 commented on redfish-core/lib/pcie_slots.hpp
> +        if (property.empty())
Here , we have sdbusplus::asio::getPropertystd::string()call, and the return value need to verify .

where as In 1030, we have asynch_method_call() for GET, and there also we are verifying the output not to be null-
const std::string* value =
std::get_ifstd::string(
&property);

                                            if (value == nullptr)
                                            {

2023-04-14 18:05 UTC, gtmills commented on redfish-core/lib/pcie_slots.hpp
> +        if (property.empty())
I really don't think it is needed. 
https://github.com/openbmc/bmcweb/blob/master/redfish-core/lib/processor.hpp#L664
This check will remove any LocationCode on D-Bus that are empty string, which we didn't have in 1030. Oh well.

2023-04-14 18:05 UTC, gtmills approved these changes

2023-04-17 13:15 UTC, merged