1050: Add Redfish total_power object
ibm-openbmc/bmcweb pull request #710
Opened 2023-06-14 01:43 UTC by lxwinspur

Fixes https://github.com/ibm-openbmc/dev/issues/3620

2023-06-14 22:16 UTC, cjcain requested changes

2023-06-14 22:16 UTC, cjcain commented on redfish-core/lib/environment_metrics.hpp
> +    constexpr std::array<std::string_view, 1> interfaces = {
This line is not needed

2023-06-14 22:16 UTC, cjcain commented on redfish-core/lib/environment_metrics.hpp
> +        constexpr std::array<std::string_view, 1> totalPowerInterfaces = {
Could use sensorInterfaces from above.

2023-06-16 08:16 UTC, lxwinspur commented on redfish-core/lib/environment_metrics.hpp
> +    constexpr std::array<std::string_view, 1> interfaces = {
Done

2023-06-19 13:37 UTC, gtmills commented on redfish-core/lib/environment_metrics.hpp
> +            BMCWEB_LOG_DEBUG << "DBUS response error";
Best if this was Error and included the ec

2023-06-19 14:02 UTC, gtmills commented on redfish-core/lib/environment_metrics.hpp
> +                    BMCWEB_LOG_DEBUG << "Can't get Power Watts!";
Best if this was Error and included the ec

2023-06-19 14:05 UTC, gtmills commented on redfish-core/lib/environment_metrics.hpp
> +         chassisId](const boost::system::error_code& ec,
`#include <boost/system/error_code.hpp>`

2023-06-19 14:14 UTC, gtmills approved these changes
Defaulting to Chris here. Would like to see my minor comments addressed but not required

2023-06-20 00:24 UTC, lxwinspur commented on redfish-core/lib/environment_metrics.hpp
> +         chassisId](const boost::system::error_code& ec,
Done

2023-06-20 16:03 UTC, gtmills commented
CI fail here: 
```
[242/243] Compiling C++ object bmcweb.p/src_webserver_main.cpp.o
FAILED: bmcweb.p/src_webserver_main.cpp.o 
c++ -Ibmcweb.p -I. -I.. -I../include -I../redfish-core/include -I../redfish-core/lib -I../http -Iconfig -I../config -flto=auto -fdiagnostics-color=never -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -std=c++20 -fno-rtti -O0 -g -fno-lto -DBMCWEB_ENABLE_BASIC_AUTHENTICATION -DBMCWEB_ENABLE_COOKIE_AUTHENTICATION -DBMCWEB_ENABLE_EVENT_SUBSCRIPTION_WEBSOCKET -DBMCWEB_ENABLE_HOST_SERIAL_WEBSOCKET -DBMCWEB_ENABLE_IBM_MANAGEMENT_CONSOLE -DBMCWEB_ENABLE_SSL -DBMCWEB_ENABLE_KVM -DBMCWEB_ENABLE_MUTUAL_TLS_AUTHENTICATION -DBMCWEB_ALLOW_DEPRECATED_POWER_THERMAL -DBMCWEB_ENABLE_REDFISH_BMC_JOURNAL -DBMCWEB_ENABLE_REDFISH_HOST_LOGGER -DBMCWEB_ENABLE_REDFISH_OEM_MANAGER_FAN_DATA -DBMCWEB_ENABLE_REDFISH_UPDATESERVICE_OLD_POST_URL -DBMCWEB_ENABLE_REDFISH -DBMCWEB_ENABLE_SESSION_AUTHENTICATION -DBMCWEB_ENABLE_STATIC_HOSTING -DBMCWEB_ENABLE_VM_WEBSOCKET -DBMCWEB_ENABLE_XTOKEN_AUTHENTICATION -Wcast-align -Wconversion -Wformat=2 -Wold-style-cast -Woverloaded-virtual -Wsign-conversion -Wunused -Wno-attributes -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -Wunused-parameter -Wdouble-promotion -Wshadow -Wno-psabi -DBMCWEB_ENABLE_LOGGING -DBMCWEB_ENABLE_DEBUG -DBOOST_ALLOW_DEPRECATED_HEADERS -DBOOST_ASIO_NO_DEPRECATED -DBOOST_ASIO_SEPARATE_COMPILATION -DBOOST_BEAST_SEPARATE_COMPILATION -DBOOST_EXCEPTION_DISABLE -DBOOST_URL_NO_SOURCE_LOCATION -DJSON_NOEXCEPTION -DOPENSSL_NO_FILENAMES -DBOOST_ASIO_DISABLE_THREADS -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_COROUTINES_NO_DEPRECATION_WARNING -MD -MQ bmcweb.p/src_webserver_main.cpp.o -MF bmcweb.p/src_webserver_main.cpp.o.d -o bmcweb.p/src_webserver_main.cpp.o -c ../src/webserver_main.cpp
In file included from ../redfish-core/include/redfish.hpp:25,
                 from ../src/webserver_main.cpp:21:
../redfish-core/lib/environment_metrics.hpp: In lambda function:
../redfish-core/lib/environment_metrics.hpp:201:64: error: ‘ec’ is not captured
  201 |                 BMCWEB_LOG_ERROR << "DBUS response error: " << ec.message();
      |                                                                ^~
../redfish-core/lib/environment_metrics.hpp:197:28: note: the lambda has no capture-default
  197 |              totalPowerPath](const boost::system::error_code& ec1,
      |                            ^
../redfish-core/lib/environment_metrics.hpp:166:54: note: ‘const boost::system::error_code& ec’ declared here
  166 |          chassisId](const boost::system::error_code& ec,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
../redfish-core/lib/environment_metrics.hpp: In lambda function:
../redfish-core/lib/environment_metrics.hpp:214:41: error: ‘ec’ is not captured
  214 |                                      << ec.message();
      |                                         ^~
../redfish-core/lib/environment_metrics.hpp:209:38: note: the lambda has no capture-default
  209 |                 [asyncResp, chassisId](const boost::system::error_code& ec2,
      |                                      ^
../redfish-core/lib/environment_metrics.hpp:166:54: note: ‘const boost::system::error_code& ec’ declared here
  166 |          chassisId](const boost::system::error_code& ec,
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

2023-06-21 00:38 UTC, lxwinspur commented
Thanks @gtmills 
Updated

2023-06-21 18:27 UTC, cjcain approved these changes

2023-06-21 19:10 UTC, merged