VMI:Not able to set static IPv6 address when DHCPv6 is enabled
ibm-openbmc/bmcweb pull request #752
Opened 2023-08-28 12:55 UTC by abhilashraju

Bug Fix for 562664.
Pre-Condition:
DHCPv4::DHCPEnabled:true
DHCPv6::OperationMode:Enabled
Try to set IPV6 static address.
IPV6 static adress is not set.

Fix:
There is an oreder mismatch in setting ip adress and disabling operation mode. Disabling operation mode should be called before setting the static Ip address. Otherwise operation mode call will reset Ip adress to zero.

Change-Id: If1337e2eccb1078e44d3cfa0902b728e0e536241

2023-08-28 19:34 UTC, gtmills commented on redfish-core/lib/hypervisor_system.hpp
> +
I don't think we want these spaces

2023-08-28 19:34 UTC, gtmills commented
Is there an upstream commit here?

2023-08-28 19:36 UTC, gtmills commented
For next time, please use a branch name that describes the commit. (e.g. fix-vmi-ipv6-address) Thanks!

2023-08-29 05:29 UTC, raviteja-b approved these changes
Please add test cases verified

2023-08-29 05:29 UTC, raviteja-b commented on redfish-core/lib/hypervisor_system.hpp
> +
+1

2023-08-29 06:57 UTC, sunharis approved these changes
Please update the test cases in the commit message. Code changes looks good

2023-08-29 06:58 UTC, asmithakarun approved these changes
If you could add some more description in the commit msg/description, it would be better

"DHCP should be disabled first when there is a static configuration request. Right now, static ip is configured and then dhcp mode is disabled causing the ip properties should be resetted"

2023-08-30 17:16 UTC, gtmills requested changes
spaces need to be addressed, please add the upstream commit, and answer any other questions. Thanks!

2023-08-30 19:20 UTC, gtmills commented
jenkins run tests please

2023-08-31 05:42 UTC, closed without merging