Fix resource dump create with multiple params (#889)
ibm-openbmc/bmcweb pull request #896
Opened 2024-04-10 13:41 UTC by isha309

Currently, resource dump redfish request takes parameters like: "Resource_<vspstring>_<password>". bmcweb will:
1. extracts the parameters with '_' as the separator
2. If there are 2 strings, it means resource dump create request is with just vsp string; if there are 3 strings, it means password is present
3. Makes a call to the backend dbus app with these extracted strings

There is no check currently to handle if more than 3 strings are present (which is an invalid usecase and error should be thrown)

Tested By:
* Created resource dump with "Resource_<str1>_<str2>_<str3>" and verified that error is sent back to the redfish client [1] POST https://${bmc}/redfish/v1/Systems/system/LogServices/Dump/Actions/LogService.CollectDiagnosticData -d '{"DiagnosticDataType":"OEM", "OEMDiagnosticDataType":"Resource_<str1>_<str2>_<str3>"}'

2024-04-10 13:44 UTC, asmithakarun commented on redfish-core/lib/log_services.hpp
> +                messages::invalidObject(
This should be similar to 
```
                    messages::invalidObject(asyncResp->res,
                                            "OEMDiagnosticDataType");
```

2024-04-10 14:28 UTC, asmithakarun approved these changes

2024-04-10 16:11 UTC, gtmills approved these changes

2024-04-10 16:12 UTC, gtmills requested changes

2024-04-10 16:12 UTC, gtmills commented on redfish-core/lib/log_services.hpp
> +                BMCWEB_LOG_ERROR << "Invalid value for OEMDiagnosticDataType";
This shoudl be a warning, user error

2024-04-12 01:02 UTC, gtmills approved these changes

2024-04-12 15:17 UTC, raviteja-b approved these changes

2024-04-15 12:39 UTC, jeaaustx commented
The latest force push included 250 commits? My email showed 250 commits which included the Audit Log commits. Audit Log is not part of 1030. Was the force push using the wrong branch?

Email excerpt:

[@isha309](https://github.com/isha309) pushed 250 commits.

    [4dbe5ec](https://github.com/ibm-openbmc/bmcweb/commit/4dbe5ec81f8e11ba5f5e8e942715d04842f40814) Implement LocationIndicatorActive for CPU resource
    [9ec664e](https://github.com/ibm-openbmc/bmcweb/commit/9ec664e7971399184865fe1680325de85a596fb0) Consume availability interface for cores (ibm-openbmc#254)
    [12f758a](https://github.com/ibm-openbmc/bmcweb/commit/12f758a6ca715945081fc9b453a5dd6e80e7e361) Add PCIe Topology Cable Links (#576)
    [c37d379](https://github.com/ibm-openbmc/bmcweb/commit/c37d37997b49b457284e5da0cc0a0146f629b8e6) bmcweb: Add PCIeSlot to Associated assembly link (#577)
    [66dbc15](https://github.com/ibm-openbmc/bmcweb/commit/66dbc153147d0faa7e9e87adfe0e96f42987bd28) Implement LocationIndicatorActive for Memory resource (#571)
[...]
[9241b34](https://github.com/ibm-openbmc/bmcweb/commit/9241b34106133ea7e4464e7eb50a8271c2a4e830) Add Audit Event Through bmcweb
[6dc7529](https://github.com/ibm-openbmc/bmcweb/commit/6dc7529e433c5a5c7f65a831a97c94278da2d7b4) Add Audit Event Points to All POSTs
[5ced90b](https://github.com/ibm-openbmc/bmcweb/commit/5ced90bd9a2af853c994bc3ec3ce2c7d02895ddd) Expand Success Case For Audit Logging (#447)
[9bd9726](https://github.com/ibm-openbmc/bmcweb/commit/9bd972697c732d5881d0e3ad4192dd99184e869d) Audit log enhancements and fixs (#500)
[db0ccb2](https://github.com/ibm-openbmc/bmcweb/commit/db0ccb2e9a7b7635395b8bba3e7950b57bea207e) Audit Log: Add PUT events to audit log for HMC config file management
[f5745fc](https://github.com/ibm-openbmc/bmcweb/commit/f5745fc670b7ce4c0987e602db222489ede89ebc) Audit Log: Exclude body data for all IBM management console events
[...]

2024-04-15 21:51 UTC, merged